#!/bin/bash

# The calling script could be wanting to run in either parallel or a single
# threaded solve operation, all you need to do is add funcions runParallel
# and runSingle respectively. It is possible that they are very similar, so
# the functions could just setup the case and then go into a common section
# this is just the entry point which is 'required'. Further, Allrun and
# Allclean has been put into this one file - it isn't really needed to have
# two different files; this also simplifies things through just having less
# files to copy from case to case

function cleanCase {
    echo "Cleaning Case"
}

function runParallel {
    echo "Running in parallel"
    startRun
}

function runSingle {
    echo "Got MPIRUN = $mpirun"
}

function startRun {
    echo "Starting run"
}
