#!/bin/bash -l
#PBS -N C100-setup
#PBS -l nodes=1:ppn=1
#PBS -l mem=100mb
#PBS -l walltime=02:00:00
#PBS -j oe
#PBS -o log.prolog

# Case Customisation,
#  In this script we customise the case, you do whatever is needed
#  except it is generally single threaded - this will usually allow
#  you to:
#  - Do mesh refinement
#
#  Do not do anything else here, we can automatically detect if you
#  were wanting to run parallel! Indeed you can even delete this file
#  if you don't need to do anything more to the case after setting
#  it up

